{% set name = "julia-parsers" %}
{% set version = "2.8.1" %}
{% set sha256 = "6ea035be48ef5daaecdff62ac8f29c6110aaf20f3349058a4f96e2503f55b693" %}
{% set julia_pkg_name = "Parsers" %}
{% set julia_pkg_uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0" %}
{% set julia_pkg_git = "https://github.com/JuliaData/Parsers.jl.git" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JuliaData/Parsers.jl/archive/refs/tags/v{{ version }}.tar.gz 
  sha256: {{ sha256 }}
  # Clone the git repository rather than the tarball so Julia can use the git information
  #git_url: {{ git_url }}
  #git_rev: v{{ version }}
  #git_depth: 1
  folder: Parsers.jl

build:
  skip: true  # [win]
  number: 0
  script_env:
    - JULIA_PKG_NAME={{ julia_pkg_name }}
    - JULIA_PKG_UUID={{ julia_pkg_uuid }}
    - JULIA_PKG_GIT={{ julia_pkg_git }}

test:
  requires:
    - julia
  commands:
    - julia -e 'using Parsers, Pkg; Pkg.test("Parsers")'

outputs:
  - name: julia-parsers
    script: build_base.sh
    build:
      noarch: generic
    requirements:
      build:
        - julia
        - sed
      host:
        - julia
      run:
        - julia
    test:
      commands:
        - julia -e 'using Parsers, Pkg; Pkg.test("Parsers")'
  - name: parsers.jl
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('julia-parsers', max_pin="x.x.x") }}
    test:
      commands:
        - julia -e 'using Parsers, Pkg; Pkg.test("Parsers")'

about:
  home: https://github.com/JuliaData/Parsers.jl
  summary: fast parsing machinery for basic types in Julia
  description: |
    A collection of type parsers and utilities for Julia.
  license: MIT
  license_family: MIT
  license_file: Parsers.jl/LICENSE
  doc_url: https://github.com/JuliaData/Parsers.jl/blob/master/README.md
  dev_url: https://github.com/JuliaData/Parsers.jl

extra:
  recipe-maintainers:
    - mkitti
    - ngam
